### ISSUE TITLE
Can this be used to pre-process source code?

### ISSUE THREAD

**Issue by tekknolagi** [ocsigen/deriving#39]
For example, if I have:

```ocaml
type t = Left of int | Right deriving (Show)

let () =
    print_endline (Show.show<t> (Left 5))
```

can I run a preprocessor on that to output OCaml code that doesn't need to build with this library?

By the way, it's not at all obvious from the docs that in order to build this snippet, I have to do:

`ocamlfind ocamlc -linkall -syntax camlp4o -package deriving -o test ./lib/deriving_Show.ml test.ml`

**Comment by hcarty** [comment]
FWIW - It may be worth checking out https://github.com/whitequark/ppx_deriving to avoid the camlp4 requirement for newer code.

**Comment by vasilisp** [comment]
You can de-sugar the syntax extension via the `-dsource` argument (or even by invoking `camlp4` directly). The command

```shell
ocamlfind ocamlc -dsource -linkall -syntax camlp4o -package deriving -o test test.ml
```

produces

```ocaml
type t =
  | Left of int 
  | Right 
module Show_t =
  (Deriving_Show.Defaults(struct
                            type a = t
                            let format =
                              function
                              | formatter ->
                                  ((function
                                    | Left v0 ->
                                        (Format.pp_open_hovbox formatter 0;
                                         (Format.pp_print_string formatter
                                            "Left";
                                          Format.pp_print_break formatter 1 2;
                                          Deriving_Show.Show_int.format
                                            formatter v0);
                                         Format.pp_close_box formatter ())
                                    | Right  ->
                                        Format.pp_print_string formatter
                                          "Right") : a -> unit)
                              
                          end) : (Deriving_Show.Show with type  a =  t))
let () =
  print_endline
    ((let module Show =
        struct
          type inline = t
          module Show_inline =
            (Show_t : (Deriving_Show.Show with type  a =  inline))
          include Show_inline
        end in Show.show) (Left 5))
```

But there is still a runtime dependency (`Deriving_Show` in the example).

Of course, I second the `ppx_deriving` suggestion :).

**Comment by tekknolagi** [comment]
@vasilisp thank you for your prompt response! Why is there a runtime dependency? What is it used for?

**Comment by vasilisp** [comment]
The library provides derivers for integers, lists, arrays, etc., e.g., your example leads to a `Deriving_Show.Show_int.format` call for the integer in `Left`. Without a library, the corresponding code would have to be duplicated.

Additionally, the derived code follows a functorial style; to support such a style the library needs to contain various signatures and functors (like `Deriving_Show.Show`, `Deriving_Show.Defaults` in your example).

**Comment by vasilisp** [comment]
If the library component causes a problem, look at `ppx_deriving`; its plugins generally produce more self-contained code.

**Comment by tekknolagi** [comment]
@vasilisp I'm adding to a codegen tool, so pulling in third-party libraries or even other files at all is undesirable.
