### ISSUE TITLE
Migrate off camlp4 

### ISSUE THREAD

**Issue by XVilka** [ocsigen/deriving#45]
Camlp4 is deprecated for a long time, Camlp5 as well. It makes sense either migrate to mehrir, or extension points for preprocessing and parsing capabilities.

See discussion about Camlp4, Camlp5, Ulex and modern OCaml here: https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985

**Comment by gasche** [comment]
ppx_deriving and ppx_type_conv replace deriving and does not depend on camlp4.
